apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-service
  namespace: argocd
  labels:
    app: webapp
    tier: frontend
spec:
  project: default
  source:
    repoURL: 'https://github.com/David-Melamed/counter-service.git'
    path: helm/counter-service/
    targetRevision: HEAD     # Git branch, tag, or commit to sync to (default is HEAD)
  destination:
    server: 'https://kubernetes.default.svc'  # URL of your Kubernetes API server; use in-cluster address for the same cluster as Argo CD
    namespace: development              # Kubernetes namespace to deploy the application to
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true