### Reusable workflow to download terraform artifact built by `tf_plan` and apply the artifact/plan ###
name: "Apply_TF_Plan"
on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Specifies version of Terraform to use. e.g: 1.1.0 Default=latest.'
        required: true
        type: string
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: true
        type: string
      region:
        description: 'Choose the AWS region to deploy to.'
        required: true
        type: string
      cluster_exists:
        required: true
        type: string
    secrets:
      cli_config_credentials_token:
        description: 'CLI config credentials token'
        required: true
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  apply-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: ${{ inputs.tf_version }}
          cli_config_credentials_token: ${{ secrets.cli_config_credentials_token }}

      - name: Terraform Init
        id: init
        run: |
          if [ "${{ inputs.cluster_exists }}" == "yes" ]; then
            echo "Cluster exists - fetching s3 state by running terraform init -reconfigure."
            terraform init -reconfigure
          else
            echo "Cluster does not exist - initializing new state by running terraform init -force-copy."
            terraform init -force-copy
          fi

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -target module.vpc 