name: "EKS-Lab"

on:
  workflow_dispatch:
    inputs:
      apply_flag:
        description: 'Set to "true" to apply changes after plan'
        required: true
        default: 'false'

jobs:
  Plan:
    uses: David-Melamed/aws-eks-terraform-modules/.github/workflows/aws_tf_plan.yml@master
    with: 
      gh_environment: eks_lab
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    if: ${{ github.event.inputs.apply_flag == 'true' }}
    uses: David-Melamed/aws-eks-terraform-modules/.github/workflows/aws_tf_apply.yml@master
    with:
      gh_environment: eks_lab
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}