jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      aws_access_key_id: ${{ steps.set_vars.outputs.aws_access_key_id }}
      aws_secret_access_key: ${{ steps.set_vars.outputs.aws_secret_access_key }}
    steps:
      - name: Set environment variables
        id: set_vars
        run: |
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID || env.AWS_ACCESS_KEY_ID }}" >> $GITHUB_OUTPUT
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY || env.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_OUTPUT

  Plan:
    needs: Setup
    uses: David-Melamed/aws-eks-terraform-modules/.github/workflows/aws_tf_plan.yml@master
    with: 
      tf_version: ${{ github.event.inputs.tf_version }}
      gh_environment: ${{ github.event.inputs.gh_environment }}
      region: ${{ github.event.inputs.region }}
    secrets:
      cli_config_credentials_token: ${{ secrets.EKS_TFC_API_TOKEN }}
      aws_access_key_id: ${{ needs.Setup.outputs.aws_access_key_id }}
      aws_secret_access_key: ${{ needs.Setup.outputs.aws_secret_access_key }}
    permissions:
      pull-requests: write
      contents: read

  Apply:
    needs: [Setup, Plan]
    if: ${{ github.event.inputs.apply_flag == 'true' }}
    uses: David-Melamed/aws-eks-terraform-modules/.github/workflows/aws_tf_apply.yml@master
    with:
      tf_version: ${{ github.event.inputs.tf_version }}
      gh_environment: ${{ github.event.inputs.gh_environment }}
      region: ${{ github.event.inputs.region }}
    secrets:
      cli_config_credentials_token: ${{ secrets.EKS_TFC_API_TOKEN }}
      aws_access_key_id: ${{ needs.Setup.outputs.aws_access_key_id }}
      aws_secret_access_key: ${{ needs.Setup.outputs.aws_secret_access_key }}
    permissions:
      pull-requests: write
      contents: read